name: "Action mine"
description: "Testing my action"
inputs: 
   message:
    description: "Message to print"
    required: true
    default: "Hola programador"

runs: 
  using: "composite"

  steps:
   - name: Inicio
     run: echo " Hola ${{ inputs.message}}"
     shell: bash