name: Test


on: [push]

jobs:
    test_build:
        runs-on: ubuntu-latest

        steps:
            - name: ls
              run: |
                echo "hola" >> hola.txt
                cat hola.txt
    
