name: Hola mundo


on: [push]

jobs:
    hola:
      runs-on: ubuntu-latest

      steps:
        - name: Hola mundo
          run : echo "Hola Mundo"

    other:
        runs-on: ubuntu-latest
      
        steps:
            - name: Intento dos
              run : ls -al

