name: Hola mundo


on: 
  push: #Ejecución del workflow cuando se haga push en las ramas especificadas
    branches:
      - master

  pull_request: #Ejecución del workflow cuando se haga pull-request en las ramas especificadas
    branches:
      - master

jobs:
    hola:
      runs-on: ubuntu-latest

      steps:
        - name: Hola mundo
          run : echo "Hola Mundo"

        - name: touch file
          run: touch hola.txt

        - name: Set text 
          run: echo "Hola mundo" >> hola.txt

        - name: Read file
          run: cat hola.txt

    other:
        runs-on: ubuntu-latest
        needs: [hola] #Necesita que el job hola se ejecute primero
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: LS
              run : ls -al

