name: Test


on: [push]

jobs:
    test_build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: ls
              run: |
                chmod +x script.sh
                ./script.sh
    
